name: Jubo
options:
  bundleIdPrefix: com.jubo
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm
    branch: main

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  Jubo:
    type: application
    platform: iOS
    sources:
      - path: Jubo
        excludes:
          - Package.swift
    entitlements:
      path: Jubo/Jubo.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jubo.app
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_CFBundleDisplayName: Jubo
        INFOPLIST_KEY_NSCalendarsUsageDescription: "Jubo uses your calendar to help answer questions about your schedule."
        INFOPLIST_KEY_NSRemindersUsageDescription: "Jubo uses your reminders to help you track tasks and to-dos."
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
        # Metal/MLX specific
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    dependencies:
      - package: mlx-swift-lm
        product: MLXLLM
      - package: mlx-swift-lm
        product: MLXLMCommon

schemes:
  Jubo:
    build:
      targets:
        Jubo: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
